### ISSUE TITLE
Unmentioned dependency to collections.OrderedDict ( "Python 2.7" ).

### ISSUE THREAD

**Issue by PixelPartner** [KelSolaar/Foundations#1]
In dataStructures.py Line 21 you call:

from collections import OrderedDict

Which is not standard for the Python 2.6.4 interpreter embedded in Maya 2012.

**Comment by KelSolaar** [comment]
Hi,

Yes you are right, I will have to put the dependencies in the README file. In fact if you take a look at the branches there is one named mpc which is the one I run at MPC for Maya usage.

Thanks for reporting that :)

Thomas

**Comment by KelSolaar** [comment]
@PixelPartner : Foundations should have support for Python 2.6 now!
